---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - networking.stakater.com
  resources:
  - routewhitelists
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.stakater.com
  resources:
  - routewhitelists/finalizers
  verbs:
  - update
- apiGroups:
  - networking.stakater.com
  resources:
  - routewhitelists/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - get
  - list
  - update
  - watch
