# permissions for end users to edit routeallowlists.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ipshield-operator
    app.kubernetes.io/managed-by: kustomize
  name: routeallowlist-editor-role
rules:
- apiGroups:
  - networking.stakater.com
  resources:
  - routeallowlists
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.stakater.com
  resources:
  - routeallowlists/status
  verbs:
  - get
