# To ensure operator doesn't manage all routes for security reason each route must add label to enable watch
# ipshield.stakater.cloud/enabled: 'true'
apiVersion: networking.stakater.com/v1alpha1
kind: RouteAllowlist
metadata:
  labels:
    app.kubernetes.io/name: ipshield-operator
    app.kubernetes.io/managed-by: kustomize
  name: routeallowlist-sample
spec:
  labelSelector:
    matchLabels:
      app: ip-test
  ipRanges:
    - 10.100.110.11
    - 10.100.110.12